packages/site-middleware/package.json, packages/site-middleware/src/compileMdx.ts, yarn.lock
Support Github Flavoured Markdown, https://github.com/remarkjs/remark-gfm
Fixes rendering of markdown table on the site.
=> feat: support github markdown syntax

packages/site-components/src/SearchInput/Results.tsx, packages/site-components/src/SearchInput/index.tsx, packages/site-components/src/SearchInput/styles.css.ts
Searches with lots of results would create a list that overflowed the bottom of the page.
This change forces the results list to only ever show a maximum of 10 results at once.
Adds a "plus {N} more..." message to show how many results a search has found.
For this PR, `MAX_RESULTS` const is hardcoded to be 10, but the plan is to expose this into the options settings for the plugin (coming in a future PR)
=> Search results-list truncation

packages/site-components/src/Sidebar/styles.css.ts, packages/theme/src/sidebar/sidebar.css.ts
Previously when at tablet breakpoint the sidebar was not full width.
=> remove fixed width of sidebar as responsive sizing is managed by theme

packages/site-components/src/Image/index.tsx
Currently an empty string would need to be passed to satisfy the type, making it optional so it can be used without an added class
=> change `nextImageClassName` type to optional

.changeset/happy-actors-cover.md, packages/plugins/src/SidebarPlugin.ts
- Add recursive sort function that orders the pages based on the sidebar priority
- Function moved to after the pages are grouped therefore the ./index page doesn't need to be pinned to the front (this code has been removed). This is because after the createGroupMap function the ./index pages are the parents and pages of the same length and routeDir are contained in the ChildNodes array
=> Sidebar priority2

.changeset/grumpy-knives-nail.md, packages/components/src/ThemeProvider.tsx, packages/site/src/pages/_app.tsx, packages/site/tsconfig.json, packages/standard-generator/src/templates/src/pages/_app.tsx.hbs, packages/standard-generator/src/templates/tsconfig.json, packages/theme/package.json, packages/theme/src/vars.css.ts, packages/theme/tsconfig.json
Replaces the use of [Global Theme Contract](https://vanilla-extract.style/documentation/global-api/create-global-theme-contract/) with a scoped [Theme Contract](https://vanilla-extract.style/documentation/api/create-theme-contract/)
This should make it easier to build and use themes.
=> Locally scoped theme contract

packages/plugins/package.json, packages/plugins/src/BrokenLinksPlugin.ts, packages/site/mosaic.config.js, patches/check-links+2.1.2.patch, yarn.lock
The `BrokenLinksPlugin` uses a running instance of mosaic to verify that all links in the source pages are alive.
If mosaic is running behind a corporate proxy, the `proxyEndpoint` option is required to fetch external URLs.
Configuration:
```json
{
modulePath: '@jpmorganchase/mosaic-plugins/BrokenLinksPlugin',
priority: -1,
// Exclude this plugin in builds
runTimeOnly: true,
options: {
baseUrl: process.env.MOSAIC_ACTIVE_MODE_URL || 'http://localhost:8080',
proxyEndpoint: 'http://some-proxy-url'
}
}
```
Console output looks like this:
```
@jpmorganchase/mosaic-site:serve: 8080 [Mosaic] Broken links found in /local/docs/publish-site-to-vercel.mdx
@jpmorganchase/mosaic-site:serve: 8080   Link to https://nextjs.org/davie is dead {
@jpmorganchase/mosaic-site:serve: 8080     type: 'link', …
```
=> feat: add `BrokenLinksPlugin`

packages/plugins/src/SidebarPlugin.ts, packages/plugins/src/__tests__/SidebarPlugin.test.ts, packages/standard-generator/src/fs.config.js
using `SidebarPlugin` options, add `rootDirGlob`
`rootDirGlob` is a glob pattern for matching directories which should be the root of the sidebar
'**' creates a root level sidebar containing all pages '*/*' creates a sidebar under each of the root directories
=> enable sidebar root(s) to be configured

.changeset/ninety-teachers-lick.md, package.json, packages/components-labs/package.json, packages/components/package.json, packages/content-editor-plugin/package.json, packages/layouts/package.json, packages/site-components/package.json, yarn.lock
#237 aimed to fix this but only affects this repo. Consumers will still be upgraded to a version of labs that mosaic doesn't support.
=> Pin @salt-ds/lab to 1.0.0-alpha.1

packages/site-components/src/VerticalNavigation.tsx
small changes to sidebar styling to fix some styles that appear broken
problems fixed
- not all buttons change styles on hover
- labels with children have different font colour than labels without children (should all be the same)
- active page is not highlighted in sidebar
- top level of sidebar has 0 left padding
I'm aware that sidebar is being redesigned, but currently I feel the Mosaic site looks unpolished and these changes can temporarily improve that.
Comparison with getting started being hovered, and on page 'Active Mode'
|Before|After|
|-----|-----|
|<img width="443" alt="Screenshot 2023-03-22 at 16 49 03" src="https://user-images.githubusercontent.com/45168453/226978396-d18eff84-c62b-43b6-a94b-70f67739821e.png">|<img width="475" alt="Screenshot 2023-03-22 at 16 38 38" …
=> fix sidebar styling 

packages/site-components/src/TableOfContents/TableOfContents.tsx, packages/site-components/src/TableOfContents/__tests__/utils.test.tsx, packages/site-components/src/TableOfContents/utils.tsx
The toc was highlighting the last item that had been scrolled past. This pr updates the logic so that it highlights the next item that has not been scrolled past.
This does mean that if there is a short section at the bottom of the page then it will not be highlighted when clicked. This seems to be a general issue in tocs, and I don't think it can be made perfectly to have scrolling and clicking in sync with these small section at the bottom edge cases.
Docusuarus have the same logic, if you click on structured content it will not be highlighted:
https://docusaurus.io/docs/seo
Stripe highlights the last item if clicked, however if you click the penultimate item it will not be highlighted:
https://stripe.com/docs/payments/checkout/how-checkout-works
=> highlight correct items in toc

.changeset/angry-mails-ring.md, packages/site-components/src/Image/index.tsx
The alt text wasn't added when <Image /> was used without fill or width and height.
=> Pass alt to Image if fill or width and height are not defined

packages/site-components/src/SearchInput/Results.tsx, packages/site-components/src/SearchInput/__tests__/searchUtils.test.tsx, packages/site-components/src/SearchInput/searchUtils.ts
When search results are displayed, they include the page route, the title of the page, and a one-line snippet of content.
When Fuse.js finds a match, it provides the line of content along with highlighting information (which characters should be bold). This is great when the "best match" on the page is part of the regular content, but leads to messy and confusing results when the best match is in either the title or route of the page: i.e. we get duplicated content being displayed, as well as *lower* information density (because we're losing the extra context provided by the one-line snippet.
This change makes search results snippet display the first line of the content when the "best match" is in the route or title (so a result will *always* include the route, title, and a useful text …
=> Prevent duplication of search results content

packages/site/mosaic.config.js, packages/site/package.json, packages/standard-generator/src/templates/mosaic.config.js.hbs, packages/standard-generator/src/templates/package.json.hbs, yarn.lock
This Pull Request adds `dotenv-load` to the Mosaic site and makes the same changes to the site generator templates. 
Users can now set NODE_ENV and the mosaic fs will read these env vars.
=> Add dotenv

.changeset/curly-apes-pay.md, packages/components/src/ThemeProvider.tsx, packages/theme/src/baseline/baseline.css.ts, packages/theme/src/index.ts
style-inject is used by salt to insert styles.  This doesn't support SSR --> https://github.com/egoist/style-inject/blob/master/src/index.js#L2
So the styling that prevents images and icons from being huge is not applied.
This change adds a class before hydration that hides `img` and `svg` elements.
This change dropped the Lighthouse perf metric from 98 down to 86.  I don't know if this is because it was being checked on a vercel preview branch rather than the main prod branch or if the change is the issue.
=> fix: hide images when SSR class is applied

.changeset/dull-carrots-drive.md, packages/cli/src/serve.ts, packages/core/src/PullDocs.ts, packages/core/src/Source.ts, packages/core/src/SourceManager.ts, packages/schemas/src/PluginModuleSchema.ts, packages/site/.env.local, packages/standard-generator/src/fs.config.js
This allows you to push a source definition to an active mosaic instance.  Do we think it should add this definition to the mosaic config file as well?
- At the moment, you could push a source definition and then if there is a restart the definition would be lost.
~~Also, disabled this in prod env.~~
- local folder definitions probably won't work, because the local folder needs to exist where mosaic is running
Post request to http://localhost:8080/sources/add
request body:
```
{
"name":"davie-docs-preview",
"definition": {
"modulePath": "@jpmorganchase/mosaic-source-git-repo",
"namespace": "davie",
"options": {
"credentials":<access-token> ,
"prefixDir": "davie",
"cache": true,
"subfolder": "docs",
"repo": "https://github.com/DavieReid/mosaic-docs.git",
"branch": "main",
"extensions": …
```
=> Dynamically add a source

.changeset/famous-mirrors-type.md, docs/quick-start/publish-site-to-aws.mdx, docs/quick-start/site-generator.mdx, packages/create-site/README.md, packages/create-site/bin/mosaic-create-site.js, packages/standard-generator/src/generator.config.js
As a Mosaic Site creator we previously installed `@jpmorganchase/mosaic-create-site` globally and run
`yarn mosaic-create-site create -o my-sample-site`
We have switched the docs to use `npx` instead to avoid the need to globally install.
When running the create, we would read `mosaic.generators.js` which read the `@jpmorganchase/mosaic-standard-generator` using `require`. The problem was that for this to work, it needed a `package.json`. This worked OK, in monorepo situations where you have a `package.json` anyway but not for creating new projects from scratch.
By switching to `npx` we need to add the temporary path of `node-modules`, so that it can require in the standard generator without needing a local package.json. Owing to the way that require searches for references, this change …
=> Improve generator

package.json, yarn.lock
Try to address --> https://github.com/jpmorganchase/mosaic/security/dependabot/15
No point upgrading swagger-ui-react as they are still using the older version of `patch-package`.  Seem to have it added erroneously as a dependency as well --> https://github.com/swagger-api/swagger-ui/blob/master/package.json#L77
=> chore: update to latest version of patch-package

.changeset/lazy-clocks-lay.md, packages/site-middleware/src/withSession.ts
The `NEXTAUTH_SECRET` env variable is not always required. It is possible to pass the secret as an option to `next-auth`
=> With session update

.changeset/wicked-horses-carry.md, packages/plugins/src/PropsTablePlugin.ts
Fix issue where component path is not resolved correctly (this was only noticeable when testing the plugin on the Salt site). I've tested on the site via a patch https://github.com/jpmorganchase/salt-ds/pull/1718.
=> Fix props table plugin component path

packages/layouts/src/LayoutBase/styles.css.ts, packages/site-components/src/VerticalNavigation.tsx
When there is not enough content to fill the page, dark mode looks awful as half the page is white.
See here --> https://mosaic-mosaic-dev-team.vercel.app/mosaic/author/index
Also fixes the label color of the active sidebar item when in dark mode.
=> fix: ensure main content area uses all available height

packages/cli/src/build.ts, packages/plugins/src/SidebarPlugin.ts
If two sources attempt to write files to the same dir, they'll each create a sidebar.json. This change catches those duplicates and merges them.
For example if SOURCE_ONE adds `developer/newsletters/index.mdx` and SOURCE_TWO adds `developer/newsletters/fascinating-newslertter.mdx`, both should be included in a single developer/newsletters/sidebar.json`
=> Merge colocated json files

.changeset/shiny-planes-deliver.md, packages/plugins/package.json, packages/plugins/src/$RefPlugin.ts, yarn.lock
When a page that is referenced via a wildcard ref **is updated**, the wildcard ref can be written into that page when the target page uses the same path as the referenced page.  This happens in the `$beforeSend` lifecycle event of the `$RefPlugin`
Page A with a wildcard ref
```
data:
items:
$ref: ./*#/data
```
Page B (a target)
```
data
title: 'a title'
```
When the wildcard ref of page A is resolved it can result in the metadata for Page B being incorrectly updated to
```
data
title: 'a title'
$ref:
'path-to-page-B#/data'
```
This is a circular ref because Page B now has a ref that points to its own data property.
=> fix: remove use of lodash `merge` from `$RefPlugin`

packages/theme/src/sidebar/sidebar.css.ts
Sidebar will always show a scrollbar on the side, especially ugly on Windows
e.g. https://mosaic-mosaic-dev-team.vercel.app/mosaic/getting-started/index
This PR hides it when not needed
=> Hide sidebar scrollbar when not needed

packages/standard-generator/src/templates/package.json.hbs
Updates to ensure site generator works and is windows compatible
=> Getting started

packages/site-components/src/TableOfContents/TableOfContents.tsx
A content review of some Salt website pages flagged the capitalization of the "On this Page" heading above the TOC links. As per our writing style guide (available on the JPM-internal UI Toolkit site), we use sentence case for page titles and headings, so it should read: "On this page" (note the lowercase 'p').
This PR fixes that and also corrects the capitalization on the `aria-label` on the `<ul>` too.
=> Change case of TOC text

packages/plugins/src/SidebarPlugin.ts
When a directory does not include and index file, the group linking in the sidebar plugin breaks because for a "group" to be identified we check for the existence of an index page.
This PR simply logs a warning and provides an indication of what directory has the problem.  Ideally we should define and upgrade the logic so that group linking can happen without the need for index pages.
To sort the sidebar you just need to add an index page.
=> fix: prevent `SidebarPlugin` from breaking when there is no index file

packages/components/src/TabsBase/TabsButton.tsx, packages/components/src/TabsBase/TabsLink.tsx, packages/components/src/TabsBase/TabsMenuButton.tsx
Salt switched from `label` to `title` for Tabs but we can support both to prevent the need for content changes.
=> fix: reintroduce support for tab `label`

.changeset/light-cherries-retire.md, packages/components/src/LinkButton.css.ts, packages/components/src/Markdown/index.tsx
Allow folks to use `LinkButton` in there docs.  Salt `Button` no longer supports `href` so a link button can be used instead.
=> feat: add `LinkButton` to mosaic markdown components

packages/schemas/src/validate.ts, packages/source-git-repo/src/index.ts
git repo source does not need to specify a schedule in it's options.
=> fix: schema validation

.changeset/rare-elephants-wave.md, packages/plugins/src/BreadcrumbsPlugin.ts, packages/plugins/src/SidebarPlugin.ts, packages/plugins/src/__tests__/BreadcrumbsPlugin.test.ts, packages/site-components/src/Breadcrumbs/Breadcrumb.tsx, packages/site-components/src/Breadcrumbs/Breadcrumbs.tsx, packages/standard-generator/src/fs.config.js
There were a few issues with breadcrumbs that have now been resolved
1. We would only ever see 3 breadcrumbs because we were checking that the page layout supports breadcrumbs.  Removed this as it causes more harm than good
2. Breadcrumb label did not match what was in the sidebar.
3. When breadcrumbs collapse into a menu button, the label was not displayed.
4. Collapsed breadcrumbs were only labels and would not navigate anywhere
5. Breadcrumb links had the file extension in the route.  Sorted by running the `PagesWithoutFileExtPlugin` with a higher priority by default.
All of the above are resolved.
=> Breadcrumbs fixes

.changeset/smooth-tables-build.md, packages/layouts/src/LayoutProvider.tsx
Provide the ability to set the default page layout at the root of a Mosaic site. Pages without `layout` in their metadata will use this layout.
=> feat: provide ability to set page default layout on LayoutProvider

.changeset/late-kings-sit.md, packages/components/src/EditionFilterView/index.tsx, packages/components/src/EditionTileLink/index.tsx
Filtering the items in the `EditionFilterView` was throwing the error:
```
`Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```
=> Fix edition filter view

.changeset/poor-students-tickle.md, packages/site-components/package.json, packages/site-components/src/500.tsx, yarn.lock
Currently if you happen to land on a broken page, you are greeted with the Mosaic Error page that asks you to return to the homepage which will reset the error status and allow you to view content again.
But a user can click the back button to a page that was working and will still see the error page.  They can use the sidebar to navigate to another page and will still see the error page.
This change updates the error page so that the error boundary status is reset when the route changes meaning you can navigate away from the broken page and see content again.  A single broken page does not impact the ability to view the working pages on the site without doing a full refresh.
=> Reset errors on nav

.changeset/tall-otters-scream.md, packages/plugins/src/BreadcrumbsPlugin.ts, packages/plugins/src/__tests__/BreadcrumbsPlugin.test.ts, packages/types/src/Volume.ts
The gist of this is:
1. Source A generates its breadcrumbs
2. Source B generates its breadcrumbs
3. Source B is notified that source A has emitted some pages
4. Source B finds its "root breadcrumb" this is the first breadcrumb present in *any* of its pages
5. From the root breadcrumb we traverse up the **global filesystem** to find pages.  This is the key because this traversal will include pages from Source A.
6. We find any additional breadcrumbs that would normally have been created if Source B pages were part of source A
7. We update all pages in Source B with the additional breadcrumbs.
Note that when doing this a bug in the types for `IUnionVolume` was identified which has been resolved as well.
=> 491 breadcrumbs need to be aware of other sources

.changeset/tall-avocados-repeat.md, packages/core/src/Source.ts, packages/core/src/SourceManager.ts, packages/core/src/__tests__/SourceManager.test.ts, packages/core/src/plugin/createPluginAPI.ts, packages/core/src/plugin/index.ts, packages/core/src/plugin/pluginRunner.ts, packages/core/src/worker/Source.worker.ts, packages/plugins/src/BreadcrumbsPlugin.ts, packages/types/src/Plugin.ts
Followup to https://github.com/jpmorganchase/mosaic/pull/492
The breadcrumbs were still not showing up from a cold start.
This PR introduces a new plugin lifecycle method `shouldUpdateNamespaceSources`.
When a source updates, **other sources that share the same namespace** will re-run `afterUpdate` if there is any plugin that returns true when `shouldUpdateNamespaceSources` is called.
This allows the other source to have a more holistic view of the namespace pages.
=> Breadcrumbs after update

.changeset/spotty-mice-share.md, jest.config.server.js, packages/cli/package.json, packages/cli/src/__tests__/serve.test.ts, packages/cli/src/plugins/mosaicAdminPlugin.ts, packages/cli/src/plugins/mosaicFastifyPlugin.ts, packages/cli/src/plugins/mosaicWorkflowsPlugin.ts, packages/cli/src/serve.ts, packages/plugins/src/__tests__/BreadcrumbsPlugin.test.ts, packages/schemas/src/MosaicConfigSchema.ts, yarn.lock
This PR replaces the [Express](https://expressjs.com/) web framework that powers the `serve` feature of the Mosaic CLI with [fastify](https://fastify.dev/)
1.  It's a good bit faster --> https://fastify.dev/benchmarks
2. It has a very nice plugin architecture --> https://fastify.dev/docs/latest/Reference/Plugins/#plugins
3. Better TypeScript support
4. It can be configured to support Express middleware (but we only use CORS middleware so not a big deal for us) --> https://github.com/fastify/fastify-express
The `serve` function is basically now the place where we register the Mosaic fastify plugins and start listening for requests.  Routes and instantiating Mosaic are done in fastify plugins.
This plugin instantiates Mosaic and adds a `mosaic` property to the fastify instance.  This allows …
=> Mosaic fastify

.changeset/ninety-coins-fetch.md, packages/plugins/src/SidebarPlugin.ts, packages/plugins/src/utils/__tests__/sortSidebarData.test.ts, packages/plugins/src/utils/sortSidebarData.ts
Users have requested the ability to sort the sidebar using a particular field in page metadata e.g. publication date.
This PR allows a user to add a sidebar sort config to an index page. For example:
```
sharedConfig:
sidebar:
sort:
field: data/publicationDate
dataType: date
arrange: desc
```
This sort config will be used to sort the pages in the *same directory* as the index page.
- `field` is the path the find the value you wish to sort by
- `dataType` is the type of the value.  it can be `string | number | Date`
- `arrange` is ascending (`asc`) or descending (`desc`)
the sidebar priority takes precedence over the shared sort config.
=> feat: provide advanced sorting for Sidebar

packages/source-http/src/__tests__/index.test.ts, packages/source-http/src/fromDynamicImport.ts, packages/source-http/src/index.ts, packages/source-storybook/src/__tests__/index.test.ts, packages/source-storybook/src/index.ts, packages/source-storybook/src/transformer.ts, packages/types/src/Source.ts
Now that the transformer is optional in the http source, it is possible for this source to return something other than a `Page[]`.
This PR exposes a generic `createHTTPSource` function that allows users to specify the response type
=> Generic http source

.changeset/quiet-walls-lay.md, packages/source-http/src/__tests__/index.test.ts, packages/source-http/src/index.ts, packages/source-http/src/proxyAgent.ts, packages/source-storybook/package.json, packages/source-storybook/src/index.ts
1. Adds a `noProxy` regex to http source. 
2. `createHttpSource` also accepts `configuredRequests` which allows users full control of the Request instance.  When provided, endpoints should not be used.  Endpoints will take precedence over `configuredRequests`
=> Storybook source proxy

.changeset/calm-pants-cheat.md, packages/site-middleware/src/withMDXContent.ts
https://mosaic-git-fix-routing-breaking-when-url-2aed10-mosaic-dev-team.vercel.app/mosaic/index?test=test will now work
where https://mosaic-git-main-mosaic-dev-team.vercel.app/mosaic/index?test=test fails
=> Fix routing breaking when URL parameters are present

packages/cli/src/plugins/createMosaicInstance.ts, packages/cli/src/plugins/mosaicFastifyPlugin.ts, packages/cli/src/serve.ts
Adding a large number of sources to mosaic increases the start time which can cause the `mosaicFastifyPlugin` to timeout.
Rather than disable or increase the timeout, this PR instantiates and starts mosaic *before* registering any fastify plugin(including mosaic ones).
This should prevent the timeout.
=> refactor: instantiate mosaic before registering fastify plugins

.changeset/plenty-foxes-search.md, packages/content-editor-plugin/src/components/PersistEditDialog/index.tsx, packages/content-editor-plugin/src/hooks/useWorkflowFeed.ts
Establish workflows websocket connection when saving is started rather than when editing is started.  Reduces the risk of connection being closed due to timeouts
=> Content Editor websocket Connection 

packages/site/package.json, packages/sitemap-component/package.json
Salt was being included in the sitemap component bundle causing styling issues.  Adding salt to the package deps of the sitemap component means it will be excluded by the node externals esbuild plugin.
=> fix: exclude salt from sitemap component bundle

.changeset/warm-tigers-return.md, packages/site-components/src/VerticalNavigation.tsx, packages/site-components/src/__tests__/VerticalNavigation.test.tsx
Fixes side component nav item not shown as active
https://github.com/jpmorganchase/salt-ds/pull/3619
=> Fix active for group with hidden nav items

.changeset/grumpy-turkeys-crash.md, packages/theme/src/baseline/baseline.css.ts, packages/theme/src/index.ts, packages/theme/src/ssrClassName.ts
Reduces the size of the baseline CSS considerably
Before: 552KB
After: 371 B (not KB)
=> Baseline css size

.changeset/weak-tigers-add.md, packages/content-editor-plugin/src/plugins/TableActionMenuPlugin.css.ts, packages/theme/src/border/border.css.ts, packages/theme/src/color/actionable.css.ts, packages/theme/src/color/beforeElement.css.ts, packages/theme/src/color/brand.css.ts, packages/theme/src/color/callout.css.ts, packages/theme/src/color/index.ts, packages/theme/src/color/lightMode.ts, packages/theme/src/color/modes.ts, packages/theme/src/color/navigable.css.ts, packages/theme/src/color/neutral.css.ts, packages/theme/src/color/selectable.css.ts, packages/theme/src/color/status.css.ts, packages/theme/src/componentExample/componentExample.css.ts, packages/theme/src/link/link.css.ts, packages/theme/src/opacity/opacity.css.ts, packages/theme/src/salt/color.css.ts, packages/theme/src/salt/salt.css.ts, packages/theme/src/shadow/shadow.css.ts
Only trying to fix link issue for #640, all other components / themes using both light / dark modes should be looked at later as well.
To confirm working, go to preview, e.g. [configure page](https://mosaic-git-fixed-link-light-dark-mode-css-mosaic-dev-team.vercel.app/mosaic/configure/index), inspect heading link, when in light mode, only light variables should be used. Same for dark mode.
```
[data-mode=light] ._651s9q3g, [data-mode=light] ._651s9q3h:hover, [data-mode=light] ._651s9q3h[data-dp-hover=true], [data-mode=light] ._651s9q3i:active, [data-mode=light] ._651s9q3j:disabled, [data-mode=light] ._651s9q3k:visited {
color: var(--mosaic-color-light-navigable-headingLink-regular);
}
```
=> Fixed link style generating light and dark modes together

.changeset/mighty-monkeys-switch.md, .changeset/perfect-cougars-grab.md, packages/site-components/src/Sidebar/styles.css.ts, packages/site-components/src/VerticalNavigation.tsx, packages/store/src/store.ts
To help Salt site, navigation component will be rendered in different density. Preview [salt-ds#4135](https://github.com/jpmorganchase/salt-ds/pull/4135)
I couldn't find any breakage on Mosaic site preview
=> Relax navigation width condition

.github/workflows/e2e.yml, packages/source-storybook/src/__tests__/index.test.ts, packages/source-storybook/src/index.ts
this will fix links to V7 storybooks which do not work without it.
=> Update storybook link url to include html doc name
