jpmorganchase/mosaic

packages/site-components/src/AppHeaderControls/index.tsx, packages/site-middleware/src/withSession.ts, packages/site/.env, packages/site/.env.local, packages/site/.env.prod
NOTE: env variable has `NEXT_PUBLIC` prefix so that the value is available client-side.
=> feat: hide login button when not logging in is disabled

docs/docs/index.mdx, docs/docs/modes/active.mdx, docs/docs/modes/snapshot-file.mdx, docs/docs/modes/snapshot-s3.mdx, docs/quick-start/publish-site-to-aws.mdx, packages/layouts/src/LayoutColumns/index.tsx, packages/plugins/src/TableOfContentsPlugin.ts, packages/site-components/src/AppHeaderDrawer/index.tsx, packages/site-components/src/Breadcrumbs/Breadcrumbs.tsx, packages/site-components/src/Sidebar/index.tsx, packages/site-components/src/Sidebar/styles.css.ts, packages/site-components/src/TableOfContents/styles.css.ts, packages/site-components/src/VerticalNavigation.tsx, packages/standard-generator/src/fs.config.js, packages/theme/src/sidebar/sidebar.css.ts
- TOC plugin was not enabled on site
- Mobile/Tablet Vertical Navigation inside a Drawer did not highlight the full row (fixed)
- refactored the sidebar style to remove redundant (left/right) and added style variants to support scrollable and sticky use-cases
=> Fix toc and mobile

packages/site-components/src/AppHeaderControls/styles.css.ts, packages/site-components/src/SearchInput/styles.css.ts
Reattaches "hide on mobile" behaviour for the search input in the header.
=> Hiding searchbar on small screens

packages/plugins/src/SidebarPlugin.ts, packages/site-components/src/Sidebar/styles.css.ts, packages/site-components/src/VerticalNavigation.tsx
Resolve issues with priority and fix sidebar width
=> Sidebar priority

package.json, yarn.lock
One for discussion, @joshwooding asked if we could pin the labs version and pip manually.
=> pin @salt-ds lab package and pip manually

packages/theme/src/salt/salt.css.ts
Salt MenuItem was updated to use theme values
=> Remove TODO's from salt.css.ts

packages/components/src/AudioPlayer/index.tsx, packages/components/src/AudioPlayer/styles.css.ts
Fix styles to centre the button bar
=> Fix styles audio player

packages/cli/package.json, yarn.lock
Fixes https://github.com/jpmorganchase/mosaic/security/dependabot/17 and https://github.com/jpmorganchase/mosaic/security/dependabot/16
=> Bump @aws-sdk/client-s3 to v3.359.0

packages/site-middleware/src/__tests__/withMDXContent.test.ts, packages/site-middleware/src/__tests__/withSearchIndex.test.ts, packages/site-middleware/src/__tests__/withSharedConfig.test.ts, packages/site-middleware/src/loaders/__tests__/createS3Loader.test.ts, yarn.lock
Follow up #393 that dedupes the yarn.lock
=> Manually dedupe @aws-sdk/client-s3

packages/components/src/LinkButton.css.ts, packages/components/src/LinkButton.tsx, packages/components/src/TabsBase/tabsMenuButton.css.ts, packages/layouts/src/LayoutBase/styles.css.ts, packages/site-components/src/AppHeader/styles.css.ts, packages/site-components/src/AppHeaderControls/index.tsx, packages/site-components/src/AppHeaderControls/styles.css.ts, packages/site-components/src/SearchInput/styles.css.ts, packages/site/e2e/layout.detailHighlight.test.ts, packages/site/e2e/layout.detailOverview.test.ts, packages/site/e2e/layout.detailTechnical.test.ts, packages/site/e2e/layout.edit.test.ts, packages/site/e2e/layout.fullWidth.test.ts, packages/site/e2e/layout.landing.test.ts, packages/site/e2e/layout.newsletter.test.ts, packages/site/e2e/layout.productDiscover.test.ts, packages/site/e2e/layout.productPreview.test.ts, packages/theme/src/button/button.css.ts
Mostly adjustung the app header design to match spec
=> Design fixes

packages/components/src/Label/index.tsx, packages/components/src/LinkText/styles.css.ts, packages/components/src/TileContentLabel/styles.css.ts, packages/plugins/src/$RefPlugin.ts
Address styling issues with Mosaic Tile component(s)
=> Tile design fixes

packages/components/src/FilterToolbar/FilterDropdown/index.tsx, packages/components/src/FilterToolbar/FilterDropdown/styles.css.ts, packages/components/src/FilterToolbar/SortDropdown/index.tsx, packages/components/src/FilterToolbar/SortDropdown/styles.css.ts
Icons have been missing since switching to salt dropdown
=> Filter toolbar design

packages/plugins/src/SharedConfigPlugin.ts
If a page did not specify any shared config metadata then it would simply create a ref to the parent directory shared-config.json file.
However, this assumes that the parent directory *has* a shared config file.
All generated shared config files are identified and then the closest 1 to the page is used.
=> fix: `SharedConfigPlugin` uses closest shared config

.changeset/hip-kangaroos-beam.md, packages/core/src/helpers/createConfig.ts, packages/plugins/src/$TagPlugin.ts, packages/plugins/src/utils/normaliseRefs.ts
Ensure `tags` work on Windows platform.
=> fix: ensure `tags` work on Windows

.changeset/silent-monkeys-notice.md, packages/store/package.json, packages/theme/package.json, packages/workflows/package.json
Missed a couple of default exports in yesterday's change
=> Fixup external repo tests

packages/site-middleware/src/withMDXContent.ts
#538 broke active mode, so here's an alternate fix
=> Fix routing breaking when in active mode

.changeset/nice-lies-boil.md, .changeset/wicked-beers-rule.md, packages/layouts/src/Fade.tsx, packages/site-components/src/TableOfContents/TableOfContents.tsx, packages/site-components/src/TableOfContents/TableOfContentsItem.tsx, packages/site/e2e/layout.detailHighlight.test.ts, packages/site/e2e/layout.detailOverview.test.ts, packages/site/e2e/layout.detailTechnical.test.ts, packages/site/e2e/layout.edit.test.ts, packages/site/e2e/layout.fullWidth.test.ts, packages/site/e2e/layout.landing.test.ts, packages/site/e2e/layout.newsletter.test.ts, packages/site/e2e/layout.productDiscover.test.ts, packages/site/e2e/layout.productPreview.test.ts
=> Refactor TableOfContents to use Salt's NavigationItem

.changeset/gorgeous-melons-swim.md, jest.config.server.js, packages/plugins/package.json, packages/plugins/src/$AliasPlugin.ts, packages/plugins/src/$CodeModPlugin.ts, packages/plugins/src/$RefPlugin.ts, packages/plugins/src/$TagPlugin.ts, packages/plugins/src/BreadcrumbsPlugin.ts, packages/plugins/src/FragmentPlugin.ts, packages/plugins/src/LazyPagePlugin.ts, packages/plugins/src/PagesWithoutFileExtPlugin.ts, packages/plugins/src/ReadingTimePlugin.ts, packages/plugins/src/SharedConfigPlugin.ts, packages/plugins/src/__tests__/FragmentPlugin.test.ts, packages/plugins/src/utils/createPageTest.ts, yarn.lock
- Moved createPageTest to a util file
- Refactored FragmentPlugin to use $afterSource
- Added tests for FragmentPlugin
=> Fix toc plugin not picking up fragments

.changeset/itchy-ghosts-grab.md, packages/components-labs/package.json, packages/components/package.json, packages/content-editor-plugin/package.json, packages/content-editor-plugin/src/components/Dialog.tsx, packages/content-editor-plugin/src/components/PersistEditDialog/index.tsx, packages/content-editor-plugin/src/components/Toolbar/InsertImage.tsx, packages/content-editor-plugin/src/components/Toolbar/InsertLink.tsx, packages/layouts/package.json, packages/site-components/package.json, packages/site-components/src/mdx.tsx, packages/site-preset-styles/package.json, packages/site/package.json, packages/sitemap-component/package.json, yarn.lock
~I would wait for https://github.com/jpmorganchase/salt-ds/pull/3157 to be released~
Checked the Dialog changes locally and it all looked fine
=> Update Salt dependencies

packages/sitemap-component/src/drawTree/styles.css.ts, packages/theme/src/salt/salt.css.ts
Migrate deprecated tokens
Result from https://github.com/origami-z/salt-codemod
=> Update Salt deprecated tokens

.changeset/big-rules-poke.md
=> Add changeset for #613

.changeset/forty-ways-mix.md, packages/components/src/ThemeProvider.tsx
Prep for potential Salt site using theme next
=> Add `themeNext` to `ThemeProvider`

.changeset/eighty-apes-float.md, docs/configure/sources/source-storybook.mdx, packages/source-storybook/package.json, packages/source-storybook/src/__tests__/index.test.ts, packages/source-storybook/src/index.ts, packages/source-storybook/src/stories.ts, packages/source-storybook/src/types/index.ts
=> Fix Storybook source not working with index.json

.changeset/fifty-peaches-change.md, .changeset/pretty-socks-judge.md, packages/plugins/src/BreadcrumbsPlugin.ts, packages/site-components/src/AppHeaderControls/index.tsx, packages/site-components/src/Breadcrumbs/Breadcrumb.tsx, packages/site-components/src/Breadcrumbs/Breadcrumbs.tsx, packages/site-components/src/Breadcrumbs/styles.css.ts
Removed @salt-ds/lab usage from breadcrumbs
Fixed missing key error
Fixed BreadcrumbsPlugin not working on Windows
=> Refactor Breadcrumbs to remove lab component usage

.github/workflows/test.yml
=> Remove Coveralls

.changeset/witty-peaches-double.md, packages/cli/src/__tests__/serve.test.ts, packages/cli/src/serve.ts
required for server healthcheck functionality
=> add actuator keepalive response for server health monitor
